CREATE TABLE Foo
(
    id INT NOT NULL,
    name VARCHAR(50) NOT NULL,
    location VARCHAR(50) NOT NULL,
    dno INT NOT NULL
 )
 
 SELECT * FROM Foo
 
 INSERT INTO Foo
 VALUES(1,'HIMANSHU','NALLASOPARA',10)
 
  INSERT INTO Foo
 VALUES(101,'PRATIK','VASAI',20)
 
  INSERT INTO Foo
 VALUES(45,'VIPUL','BORIVALI',100)
 
  INSERT INTO Foo
 VALUES(6,'KRISHNA','ANDHERI',50)
 
 ALTER TABLE Foo
 ADD CONSTRAINT PK_Foo PRIMARY KEY (id)
 
 EXECUTE sp_helpindex Foo
 
 CREATE NONCLUSTERED INDEX non_cluster_index
ON Foo(dno ASC)

SELECT * 
FROM Foo
WHERE id=101

SELECT * 
FROM Foo
WHERE dno=50

use AurionPro