use AurionPro

CREATE TRIGGER Emp_NameUpperCase
  ON EMP 
  FOR INSERT
  AS
	BEGIN
		UPDATE EMP
		SET ENAME=UPPER(ENAME)
	END;
	
	
INSERT INTO EMP VALUES (7939,'anshu','CLERK',7782,'23-JAN-82',1000,NULL,10);
SELECT *
FROM EMP;