CREATE VIEW [MYDB] AS 
SELECT ENAME,DEPTNO,JOB,SAL
FROM EMP

SELECT * 
FROM [MYDB]

--INSERT MYDB(EMPNO,ENAME,DEPTNO,JOB,SAL)
--VALUES(45,'Himanshu',50,'SALESMAN',2000) 

--CREATE OR REPLACE VIEW [MYDB] AS
--SELECT ENAME,DEPTNO,JOB,SAL,HIREDATE
--FROM EMP

use AurionPro
