// <auto-generated />
namespace ManyToMany_EF_Relation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class CreateManytoMany_ActorMovie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateManytoMany_ActorMovie));
        
        string IMigrationMetadata.Id
        {
            get { return "201807140719094_CreateManytoMany_ActorMovie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
